name: Node.js CI

on: 
  push:
    branches: [ main ]

jobs:
  build1:
   
    runs-on: self-hosted
    env:
         CI: false
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd server
      - run: npm i
      - run: cd ..
      - run: npm i
#       - run: npm run build --if-present
      - run: npm run start
#       - run: npm install -g serve
#       - run: serve -s build
      
#   build2:
   
#     runs-on: self-hosted
#     env:
#          CI: false
#     strategy:
#       matrix:
#         node-version: [14.x]
        
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - run: cd server
#       - run: npm i
#       - run: npm run build --if-present
#       - run: serve -s build

